### ISSUE TITLE
Error: Pip install not working

### ISSUE THREAD

**Issue by KuechlerO** [dvklopfenstein/pmidcite#42]
Hey & thx for your tool!

**My issue:**
After installing pmidcite via `pip install pmidcite` calling `icite` does not work.

**Error:**
 `-bash: icite: command not found`

**Comment by dvklopfenstein** [comment]
Hello! So happy that you are interested in *pmidcite*

I have added an entry_point in the setup.py file so that it loads `icite` in addition to the script, `icite.py`

Please download the new version from PyPi and give the install a try.

Or install from a locally cloned copy:
```
$ git clone https://github.com/dvklopfenstein/pmidcite.git
$ cd ./pmidcite
$ pip install .
```

**Comment by KuechlerO** [comment]
Thanks for your efforts!

Installing it locally via cloning & `pip3 install .` and afterwards calling `icite.py <pubmed_ID>` did work :)

However, without cloning neither installing via `pip` or `pip3` did work:

**With pip**:
```
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ pip install pmidcite
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pmidcite
  Downloading https://files.pythonhosted.org/packages/73/65/e2d6f0769eb6a6ec572c43c93cd5b57f880fb660863637bf0c811c10e4a5/pmidcite-0.0.38-py2.py3-none-any.whl (2.6MB)
     |████████████████████████████████| 2.6MB 2.1MB/s 
Installing collected packages: pmidcite
Successfully installed pmidcite-0.0.38
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ icite
Traceback (most recent call last):
  File "/usr/local/bin/icite", line 5, in <module>
    from src.bin.icite import main
ImportError: No module named src.bin.icite
```

**With pip3**:
```
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ pip3 install pmidcite
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pmidcite
  Using cached pmidcite-0.0.38-py2.py3-none-any.whl (2.6 MB)
Installing collected packages: pmidcite
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pmidcite-0.0.38
WARNING: There was an error checking the latest version of pip.
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ icite
Traceback (most recent call last):
  File "/usr/local/bin/icite", line 5, in <module>
    from src.bin.icite import main
ModuleNotFoundError: No module named 'src'
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ 
```

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest in pmidcite and for your time to open issues #42 and #43. 

I have put the script code into a new pmidcite.scripts module, which is now accessed in the setup.py console_scripts entry_points. Hopefully, this will resolve the install issues.

Please check try to re-install if you have the time. 

Thank you again for your contributions to this project.

**Comment by KuechlerO** [comment]
Thx for your quick responses! :)

Yes, with pip3 it's working now:
**pip3**:
```
(pmidcite_env) Olivers-MacBook-Pro-5:~ oliverkuchler$ pip3 install pmidcite
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pmidcite
  Using cached pmidcite-0.0.40-py2.py3-none-any.whl (2.6 MB)
Installing collected packages: pmidcite
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pmidcite-0.0.40
WARNING: There was an error checking the latest version of pip.
(pmidcite_env) Olivers-MacBook-Pro-5:~ oliverkuchler$ icite 25518870 
TOP 25518870 .. HA..c  97 3 2015   182  1 138 au[01](Darrell Sleep) Albumin and its application in drug delivery.
```

And again for documentation here my output with pip (using python 2.7), throwing errors. I wouldn't bother too much about it since the Python 3 is supported by pip3 otherwise...

**pip**:
```
(pmidcite_env) Olivers-MacBook-Pro-5:~ oliverkuchler$ pip install pmidcite
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pmidcite
  Using cached https://files.pythonhosted.org/packages/ae/0b/63c8169bc3e56656f8e9bfc9bf96ee68e6a132522130855c175daeb4a5ca/pmidcite-0.0.40-py2.py3-none-any.whl
Installing collected packages: pmidcite
Successfully installed pmidcite-0.0.40
(pmidcite_env) Olivers-MacBook-Pro-5:~ oliverkuchler$ icite 25518870 
Traceback (most recent call last):
  File "/usr/local/bin/icite", line 5, in <module>
    from pmidcite.scripts.icite import main
  File "/usr/local/lib/python2.7/site-packages/pmidcite/scripts/icite.py", line 6, in <module>
    from pmidcite.cli.icite import NIHiCiteCli  # get_argparser
  File "/usr/local/lib/python2.7/site-packages/pmidcite/cli/icite.py", line 9, in <module>
    from pmidcite.eutils.cmds.pubmed import PubMed
  File "/usr/local/lib/python2.7/site-packages/pmidcite/eutils/cmds/pubmed.py", line 11, in <module>
    from pmidcite.eutils.cmds.base import EntrezUtilities
  File "/usr/local/lib/python2.7/site-packages/pmidcite/eutils/cmds/base.py", line 29, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```

Thank you very much for your work!
