### ISSUE TITLE
Makefile does not execute completely

### ISSUE THREAD

**Issue by KuechlerO** [dvklopfenstein/pmidcite#43]
Hi,

I'm trying to set-up your tool manually by cloning this repo and running your Makefile, but the makefile doesn't seem to create the necessary files (but rather stops after executing just 2 find-commands). Could you please add some lines of explanation, how to set-up your tool manually?

Thank you so much for your efforts! Looking forward to testing your tool :)

Here my Makefile print-out:
```
make -f makefile
find src -regextype posix-extended -regex ".*[a-z]+.py"
src/bin/dnld_pmids.py
src/bin/rpt_dates_top.py
src/bin/plot_pubmed_contents.py
src/bin/plt_guassian_nihperc.py
src/bin/scatter.py
src/bin/query_pubmed.py
src/bin/dnld_pubmed.py
src/bin/icite.py
src/bin/read_pmids.py
src/tests/args_dflt.py
src/tests/pmids_many.py
src/tests/test_cfg_icite.py
src/tests/test_nb_print_paper_sort_cites.py
src/tests/test_paper_sorts.py
src/tests/test_nb_nihocc_data_download_always.py
src/tests/test_speed_api_dnld.py
src/tests/dnld_pmids_100k.py
src/tests/test_cli_icite.py
src/tests/test_nb_print_paper_all_refs_cites.py
src/tests/prt_hms.py
src/tests/test_nb_query_pubmed.py
src/tests/test_nb_nihocc_data_download_or_import.py
src/tests/icite.py
src/tests/pmids.py
src/tests/test_dnld_cites_refs.py
src/tests/test_speed_dnld_load.py
src/tests/test_database_list.py
src/tests/test_icite_longreq.py
src/tests/test_print_paper.py
src/tests/test_dnld_pmids.py
src/pmidcite/eutils/cmds/pubmed.py
src/pmidcite/eutils/cmds/efetch.py
src/pmidcite/eutils/cmds/elink.py
src/pmidcite/eutils/cmds/cmdbase.py
src/pmidcite/eutils/cmds/esearch.py
src/pmidcite/eutils/cmds/base.py
src/pmidcite/eutils/cmds/query_ids.py
src/pmidcite/eutils/pubmed/terms.py
src/pmidcite/eutils/pubmed/query.py
src/pmidcite/eutils/pubmed/author.py
src/pmidcite/eutils/pubmed/qualifiers.py
src/pmidcite/eutils/pubmed/descriptors.py
src/pmidcite/eutils/pubmed/rdwr.py
src/pmidcite/eutils/pubmed/record.py
src/pmidcite/eutils/pubmed/authors.py
src/pmidcite/eutils/pubmed/counts/dnlded_data.py
src/pmidcite/eutils/pubmed/counts/dnld.py
src/pmidcite/eutils/pubmed/counts/plt.py
src/pmidcite/eutils/pubmed/counts/data.py
src/pmidcite/cfg.py
src/pmidcite/pubmedqueryicite.py
src/pmidcite/plot/nih_perc.py
src/pmidcite/plot/scatter.py
src/pmidcite/utils_module.py
src/pmidcite/_version.py
src/pmidcite/icite/pmid_dnlder.py
src/pmidcite/icite/downloader.py
src/pmidcite/icite/papers.py
src/pmidcite/icite/paper.py
src/pmidcite/icite/api.py
src/pmidcite/icite/utils.py
src/pmidcite/icite/entry.py
src/pmidcite/icite/dnldr/pmid_dnlder.py
src/pmidcite/icite/dnldr/pmid_loader.py
src/pmidcite/icite/dnldr/pmid_dnlder_base.py
src/pmidcite/icite/dnldr/pmid_dnlder_only.py
src/pmidcite/icite/nih_grouper.py
src/pmidcite/cli/readpmids.py
src/pmidcite/cli/rptdatestop.py
src/pmidcite/cli/querypubmed.py
src/pmidcite/cli/entry_keyset.py
src/pmidcite/cli/utils.py
src/pmidcite/cli/icite.py
src/pmidcite/cli/dnldpubmed.py
src/pmidcite/cfgini.py
find src -regextype posix-extended -regex "[a-z./]*" -type d
src
src/bin
src/tests
src/tests/data
src/pmidcite
src/pmidcite/eutils
src/pmidcite/eutils/cmds
src/pmidcite/eutils/pubmed
src/pmidcite/eutils/pubmed/counts
src/pmidcite/plot
src/pmidcite/icite
src/pmidcite/icite/dnldr
src/pmidcite/cli
```

Tested on MacOS-System.

**Comment by dvklopfenstein** [comment]
Hello! Thank you for your interest in *pmidcite* and for you question.

I have changed the first make target to one that builds and installs *pmidcite* from a locally cloned copy. Please give it a try and let me know how it goes.

**Comment by KuechlerO** [comment]
Very cool, thank you!

Unfortunately that does not work for me, since in my case `pip3` instead of `pip` has to be called. But that is rather a system/environment set-up problem. Calling manually `pip3 install .` and using `icite.py` subsequently works for me.

However, for the sake of documentation, here's my shell output:
```
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ git clone https://github.com/dvklopfenstein/pmidcite.git
Klone nach 'pmidcite' ...
remote: Enumerating objects: 4072, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 4072 (delta 125), reused 146 (delta 93), pack-reused 3872
Empfange Objekte: 100% (4072/4072), 19.62 MiB | 5.71 MiB/s, fertig.
Löse Unterschiede auf: 100% (2543/2543), fertig.
(pmidcite_env) 87-77-90-53:Years oliverkuchler$ cd pmidcite
(pmidcite_env) 87-77-90-53:pmidcite oliverkuchler$ make
pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Users/oliverkuchler/Studium/Apollo/Work/consultancy/Years/pmidcite
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/setup.py'"'"'; __file__='"'"'/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/pip-egg-info
         cwd: /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/setup.py", line 68, in <module>
        long_description=get_long_description(),
      File "/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-req-build-q_jroC/setup.py", line 33, in get_long_description
        with open(join(dir_cur, 'README.md'), encoding='utf-8') as ifstrm:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [install] Error 1
```

**Comment by KuechlerO** [comment]
I gave `make` another run, here's the output:

```
(base) Olivers-MacBook-Pro-5:pmidcite oliverkuchler$ make
pip3 install .
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/oliverkuchler/Studium/Apollo/Work/consultancy/Years/pmidcite
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info
      writing /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info/entry_points.txt
      writing top-level names to /private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info/top_level.txt
      writing manifest file '/private/var/folders/2h/x3d2xrpd66908__bf_8j7sqc0000gn/T/pip-pip-egg-info-df__155e/pmidcite.egg-info/SOURCES.txt'
      error: package directory 'src/src' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
make: *** [install] Error 1
```

**Comment by dvklopfenstein** [comment]
In the setup.py file, do you see this:
```
PACKAGES = [
    'pmidcite',
    'pmidcite.cli',
    'pmidcite.eutils',
    'pmidcite.eutils.cmds',
    'pmidcite.eutils.pubmed',
    'pmidcite.eutils.pubmed.counts',
    'pmidcite.icite',
    'pmidcite.icite.dnldr',
    'pmidcite.scripts',
    'pmidcite.plot',
]
```

If not, please do a `git pull`

Thanks for retrying this. I appreciate your time. Your efforts have certainly improved this project for all

**Comment by dvklopfenstein** [comment]
I just merged this PR, which should fix the issue
https://github.com/dvklopfenstein/pmidcite/pull/46

**Comment by KuechlerO** [comment]
Yes, now it work. Thx!
